### ISSUE TITLE
req.nextUrl.clone is not a function

### ISSUE THREAD

**Issue by tylerjharden** [vercel/platforms#68]
Seeing this issue running dev locally in the _middleware.js

I'm unsure why I am having this issue, as I have brought parts of this repo into an existing Next.js project. Let me know what specific details I need to share and I will update the issue accordingly.

![image](https://user-images.githubusercontent.com/7143160/155269231-9b0e1d30-b994-4684-8e6e-06339ccfae85.png)

**Comment by tylerjharden** [comment]
Updating to ^12.0.11-canary.8 fixed this. Unsure why.

**Comment by jmotes** [comment]
@tylerjharden why not go all the way to 12.1?

**Comment by tylerjharden** [comment]
I did, working fine with 12.1.0
